language: php

services:
  - couchdb

php:
  - 5.5
  - 5.6
  - 7.0

notifications:
  slack:
    rooms:
      - det:YiOiwfzUBtt9aTnWvocK8uDI
    on_success: change
    on_failure: always
    on_start: never

before_install:
  - composer selfupdate

install:
  - composer install
